#DEBUG=True
SECRET_KEY='RANDOM SHIT'
SQLALCHEMY_DATABASE_URI='mysql://user:pass@host/database'
SCRIPTS_DIR='/path/to/scripts'

SESSION_COOKIE_SECURE=True
PERMANENT_SESSION_LIFETIME=3600
SESSION_REFRESH_EACH_REQUEST=True
